### ISSUE TITLE
No Backup for Gitlab Repos that I am not the Creator

### ISSUE THREAD

**Issue by zarinbal** [jonhadfield/soba#12]
Hi

When I run the Soba (v 1.1.3 beta) on my Gitlab account, I only back up the repositories I created. If I am not the creator of a repository, it does not back it up. Even if I have the "Owner" role of the repository, it does not do that.  (It is the same for any other role like maintainer, developer, or reporter.)

This happens in three cases:
1- I have a Group that I created. My team members created many projects in my group, and I have the Owner role. But I can not back them up.
2- I have a separate account responsible for backup tasks with read-only (guest /reporter) access to repos (security reasons). This user can not back up anything. 
3- I want to back up a subset of my repositories, and I created an account with read-only access to a subset of my repositories (e.g., a group). This user can not back up anything. 

How can I solve this issue?

**Comment by jonhadfield** [comment]
Hi, sorry for the delay.  I've just put out a new beta release [1.1.3-beta.2](https://github.com/jonhadfield/soba/releases/tag/1.1.3-beta.2) that I'm hoping will help.
For 1 and 2: I've changed the way in which Groups are retrieved. It should now return all Groups you have a minimum access level of Guest for, regardless of who owns or creates.  
For 3: If I've understood correctly, the new beta should resolve this also. There are more details on the release page about how to override the min access level, in case it's now retrieving too many Groups. If you mean you want to actually specify a subset of Groups to return, I'm trying to avoid a situation where env vars are used for storing lots of data, e.g. a list of Group references, and hope the min access level change (and ability to override) will cover most use-cases.

I have little user experience with GitLab and have made numerous assumptions. Any feedback would be appreciated.

**Comment by zarinbal** [comment]
> 

Awesome. I will try it and will give you feedback. I have used Gitlab extensively and I would be happy to help you in providing feedback and coding. 

Re 3, That is all right. I think, if I define a user that has access to certain Groups/Repos, tat should solve this case.

**Comment by jonhadfield** [comment]
I've just made another change, as detailed here: https://github.com/jonhadfield/soba/issues/11#issuecomment-1264619177  
Please let me know how you get on.

**Comment by jonhadfield** [comment]
Feedback on that related [issue](https://github.com/jonhadfield/soba/issues/11) suggests all of those points should now be resolved. Note: I'm calling the /projects API endpoint as the /groups endpoint doesn't apply across the whole of gitlab.   

The latest version is here: https://github.com/jonhadfield/soba/releases/tag/1.1.3-beta.5   
  
Please let me know if that does what you need.

**Comment by jonhadfield** [comment]
Closing, but please shout if you experience any issues.
