### ISSUE TITLE
Add Kubernetes setup instructions for running with cron

### ISSUE THREAD

**Issue by jonhadfield** [jonhadfield/soba#3]

**Comment by xXluki98Xx** [comment]
Hi @jonhadfield,
what exactly needs to be done?

**Comment by jonhadfield** [comment]
I'm thinking of adding a Helm chart, or maybe just simple instructions for running in kubernetes. I currently run on a Synology NAS, but I can see Ops teams running this as one of a bunch of tools in a cluster to avoid running VMs.  
I suspect most Ops people would already know how to do this, considering soba is already available as a docker image and configured using environment variables.   

I did start working on a helm chart, but simply haven't had time nor seen the demand yet.

**Comment by jonhadfield** [comment]
I've just updated documentation to include Kubernetes cron job setup instructions, and added sample manfifest files.
