### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xXluki98Xx** [jonhadfield/soba#36]
Hi, as a user I have a slow start because I already fail at the correct token for Gitea.

Could you expand the readme and check the current configurations, I think it's a bit inconsistent.

**Comment by jonhadfield** [comment]
Hi @xXluki98Xx,  
Yes, the instructions linked to are for using the API to get tokens, but I should have provided more user-friendly instructions, as I have for the other providers.  
I'll update/add a link shortly.  
In the meantime, after logging into the Gitea web interface, click on your user icon in the top right-hand corner and go to `Settings`. From there, choose `Application`. Add a token name, e.g. "RepoBackups".  
Expand the `Select permissions` list and then select Organisation Read and Repo Read permissions. _Let me know if you get any errors with that_.  
Then click on `Generate Token` and you'll see some text at the top of the screen like this: `7d1aa88124c304dbbd5cbbf41766e0a2fe03ff0a`.  That's the value you need to set for environment variable `GITEA_TOKEN`. For `GITEA_APIURL` use: `https://my.domain.com/api/v1`.  

Hope this helps, and thanks for the feedback.

**Comment by xXluki98Xx** [comment]
Hi @jonhadfield,

Many thanks, it works now.

Also I'm not sure if i should open an other Ticket, but with GITEA_ORGS="*", I can get limited but not private Organisations.

**Comment by jonhadfield** [comment]
If you wouldn't mind creating a new ticket, I'll take a look asap.

Thanks

**Comment by jonhadfield** [comment]
Instructions updated in 9d4df28.
