### ISSUE TITLE
Feature: Advanced Scheduler

### ISSUE THREAD

**Issue by xXluki98Xx** [jonhadfield/soba#37]
As a User I want be able to make backups under 1 hour, like every 5 or 10 minutes.

DoD:
- it should be possible to use the scheduler with hours or minutes.

**Comment by jonhadfield** [comment]
Hi @xXluki98Xx,

I've just implemented that now and pushed a [new release](https://github.com/jonhadfield/soba/releases/tag/1.2.3).
It's not yet documented, but you can now specify a number followed by either 'm' or 'h', e.g.  `export GIT_BACKUP_INTERVAL=30m` where `m` simply means minutes.  
The default remains as hours (without a following letter) for backwards compatibility.

Let me know how you get on with it.

**Comment by xXluki98Xx** [comment]
Hi @jonhadfield,
it works perfectly.
