### ISSUE TITLE
Bug: Sync All Organisations on Gitea

### ISSUE THREAD

**Issue by xXluki98Xx** [jonhadfield/soba#38]
As a user, I want to sync all organizations with all repositories I am a member of.

Bug:
- When I set GITEA_ORGS='*', only public and restricted organizations are synced.

**Comment by jonhadfield** [comment]
Hi @xXluki98Xx, I'm unable to recreate this. Please could you try again with: https://github.com/jonhadfield/soba/releases/tag/1.2.3.  
Can you also try using double quotes around the asterisk?

**Comment by xXluki98Xx** [comment]
Hi @jonhadfield, I figured it out.
It was not the asterisk problem, but the user must be a site admin.

**Comment by jonhadfield** [comment]
Great. Thanks for the update.
