### ISSUE TITLE
Feature Request(?): Trigger Repo Sync via Webhook

### ISSUE THREAD

**Issue by xXluki98Xx** [jonhadfield/soba#39]
(If it makes sense to you too).

As a user, I want to be able to trigger a sync event/cycle when there is a new commit.

DoD:
- Endpoint to trigger sync

**Comment by jonhadfield** [comment]
Hi @xXluki98Xx, What use-case do you have in mind? By using the `refs` mode for compare, you could schedule to run every couple of minutes to ensure backups are taken frequently.

Adding a listener to soba (to receive webhooks) adds **a lot** of complexity and I'm not sure it would be a popular requirement, although happy to be proven wrong.

**Comment by xXluki98Xx** [comment]
Hey, indeed a minimal frequency seems to be enough.
