### ISSUE TITLE
Callback URL in BitBucket OAuth consumer

### ISSUE THREAD

**Issue by r3mi** [jonhadfield/soba#50]
Hello,

thanks for this tool, very useful !
I had troubles to make it work for Bitbucket. I tried several settings, but "listing Bitbucket repositories" always returned nothing.
In the end, what worked is : adding a "Callback URL" when creating the workspace OAuth consumer in Bitbucket. 
Setting a dummy URL did the trick (`http://example.com/`).
Unfortunately, there is no error when "Callback URL" is empty (no error in Bitbucket settings, no error when running soba), but : the list of repos is always an empty list.

May be possible to mention this setting in the doc ?

Also, when trying accessing Bitbucket end points from `curl` (`https://bitbucket.org/site/oauth2/access_token`), it seems there is normally an error returned by Bitbucket in this situation (400/`{"error": "invalid_request", "error_description": "No callback uri defined for the OAuth client."}`) : may be it is silently ignored by soba ?

**Comment by jonhadfield** [comment]
Hi, thanks for the feedback.
I'll take a look asap.

**Comment by jonhadfield** [comment]
Hi, I've done some testing and found that it's not just a missing callback URL that causes an issue, but also if the following option isn't checked:
```
[ ] This is a private consumer
Enables the client_credentials grant type. Installable applications that ship their OAuth consumer credentials as part of the application should not be marked as private. 
```
The difference with BitBucket and the other providers is that BitBucket returns an HTTP 200 (Success) response when there's an auth failure response, so soba continued as if nothing was wrong. 

I've modified a dependency https://github.com/jonhadfield/githosts-utils/commit/f5981bc0a6ec4a2a69fb25a892ceb4565c640269 to ensure any errors are captured and returned.
...and put out a new release: https://github.com/jonhadfield/soba/releases/tag/1.2.7

Without callback uri defined:  
`soba: 2024/01/16 11:22:55 bitbucket.go:226: failed to get bitbucket auth token: invalid_request - No callback uri defined for the OAuth client.`

Without setting OAuth consumer as a private consumer:  
`soba: 2024/01/16 11:22:27 bitbucket.go:226: failed to get bitbucket auth token: invalid_grant - Cannot use client_credentials with a consumer marked as "public". Calls for auto generated consumers should use urn:bitbucket:oauth2:jwt instead.`

I'll put a note in the documentation also.

Thanks again for flagging, and let me know if you notice any issues.

**Comment by r3mi** [comment]
thanks, works great!
