### ISSUE TITLE
Authentication errors just exit

### ISSUE THREAD

**Issue by r3mi** [jonhadfield/soba#54]
Hello,
thanks for the notification webhook feature, works great !

I noticed an issue: when there is an authentication failure (e.g. GitHub token expired), there is no failure notification sent with webhook. 
Also, it seems the `GIT_BACKUP_INTERVAL` schedule is ignored in that case, and soba just exits. 
Which means when using automated restart (eg docker-compose with `restart` policy), it just loops on error, and hammers the provider with failed authentication attempts.

Is there a mean to handle this case as a "regular" error ? eg failure notification + next attempt according to schedule ?

**Comment by jonhadfield** [comment]
Hi, from a basic cli sense, I wanted to just print the error and exit. That way the user has their feedback and can correct before trying again.  That logic allowed me to output errors (and store for webhook summaries) and continue running for non-catastrophic issues.
I see how this isn't a good fit for running something wrapped in some logic that says "on error, do it again asap". For obvious reasons, I don't include any code to report back to me (even anonymously) how this app is used or when and why it errors, so it's impossible to know the priority, nor impact, of attempting to improve this logic.  I may look to make that an explicit opt-in feature (no nagging in the app etc., but something mentioned in the README.md) in future.
I've had a look at the code base and it's a non-trivial change that could take some time to implement behaviour that caters for CLI, Cron, Kubernetes Cron, and Docker-Compose users. It's daunting to think of how to even automate testing for all those scenarios, but I know it's a must.  
Whilst it makes sense to send a Webhook if the app does fail, I'm also conscious of thrashing your web hook receiver, so first need to work out how to ensure a delay after quick exit.   

Please excuse the rambling. I think the tl;dr version is: I'll work on it, but it'll take time, and would it be possible to use a [restart policy](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#restart_policy) on docker-compose in the meantime?

**Comment by r3mi** [comment]
Yes, I did that : `restart: on-failure:3`  to avoid being stuck in a failed auth loop, and then I can be alerted from monitoring tools.
Thanks for the explanation!

**Comment by jonhadfield** [comment]
Hi @r3mi,
I've put out [1.2.14](https://github.com/jonhadfield/soba/releases/tag/1.2.14) that hopefully addresses the error handling and api thrashing.  
In case of any initial failures like provider authentication, I collect the error and let the other providers continue. On completion, the webhook will now contain the error, plus the error stack to show where in the code it failed.  
If soba's running non-daemonized, it should now also return the correct exit code, i.e. 0 for success and 1 for failure.

**Comment by r3mi** [comment]
thanks ! works fine !

**Comment by jonhadfield** [comment]
Thanks for the feedback. Will close.
