### ISSUE TITLE
docker releases

### ISSUE THREAD

**Issue by r3mi** [jonhadfield/soba#74]
Hello,
I can't find the recent release in docker: 1.2.18 and 1.2.19 (ghcr or docker hub) ; is there a new repo ?

thanks for soba !

**Comment by jonhadfield** [comment]
Thanks for raising @r3mi!
The new docker images are now there.  The issue was simply that I'd pushed the new tags before generating the build. It has to be build first as the tag triggers the GitHub action that releases the docker images that include the new build.
