### ISSUE TITLE
Kaspersky detects VHO:Trojan.Win32.Sdum.gen in soba_1.1.1_windows_amd64.tar

### ISSUE THREAD

**Issue by tekord** [jonhadfield/soba#8]

**Comment by jonhadfield** [comment]
Thanks for flagging. I have had this once before, but with another app IIRC.  
It seems it's quite common to get a false-positive: https://go.dev/doc/faq#virus. For example:  
- https://github.com/golang/go/issues/3328
- https://github.com/lian/msfs2020-go/issues/14

I'll add something to the README to clarify why it may be flagged. It seems there's no solution, except for the AV companies to modify their scanners.
