### ISSUE TITLE
GitLab Group projects do not get backed up

### ISSUE THREAD

**Issue by hargitaigabor** [jonhadfield/soba#9]
Hi! Does soba support backing up GitLab Groups?

I've just finished moving most of my projects into their appropriate Groups and it seems that soba does not pick up projects that are part of a Group. Am I missing something in terms of configuration?

**Comment by jonhadfield** [comment]
Hi, it's currently retrieving projects by user id and then retrieving repositories that way. The GitLab API suggests it won't be too difficult to discover projects by group also, so will take a look.

**Comment by drummingdemon** [comment]
> Hi, it's currently retrieving projects by user id and then retrieving repositories that way. The GitLab API suggests it won't be too difficult to discover projects by group also, so will take a look.

Awesome, thanks so much! 👍

**Comment by jonhadfield** [comment]
I've just put out release [1.1.2](https://github.com/jonhadfield/soba/releases/tag/1.1.2) that now includes retrieving projects by group. I've not had much time to work on it, so some bits like pagination of results are currently missing (only first 20 groups and projects).    
Let me know if there are any issues and, if all good, I'll create an issue to track the remaining tasks.

**Comment by drummingdemon** [comment]
> I've just put out release [1.1.2](https://github.com/jonhadfield/soba/releases/tag/1.1.2) that now includes retrieving projects by group. I've not had much time to work on it, so some bits like pagination of results are currently missing (only first 20 groups and projects).
> Let me know if there are any issues and, if all good, I'll create an issue to track the remaining tasks.

Just pulled the updated Docker container, bundled all the repos from all of the Groups - works like a charm!

Your feedback and quick fix are much appreciated, think we can close this one now - looking forward to the pagination here as well!
